const { getTopicDirs } = require('./scripts/topics');

/**
 * Builds one sidebar per topic folder under docs/, each scoped to only
 * that topic's files (plus the Introduction page). This means visiting
 * a Linux page only shows Linux items in the sidebar, not every topic.
 *
 * Adding a new topic later is just "add a folder under docs/ with a
 * _category_.json" - no manual edits needed here.
 */
const sidebars = {};

for (const topic of getTopicDirs()) {
  sidebars[`${topic}Sidebar`] = [
    'intro',
    {
      type: 'category',
      label: topic.charAt(0).toUpperCase() + topic.slice(1),
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: topic }],
    },
  ];
}

module.exports = sidebars;
