/**
 * Sidebar configuration.
 *
 * One sidebar per topic, each scoped to that topic only, so browsing Docker
 * never shows Kubernetes pages. Plus a dedicated sidebar for the intro page.
 *
 * Everything is generated from the docs/ tree. Adding a topic folder, a page,
 * or a grouped subfolder requires no edit here — `autogenerated` walks
 * subdirectories and picks up their _category_.json for grouping.
 *
 * @see https://docusaurus.io/docs/sidebar
 */

const { getTopicDirs, shouldCollapseTopic } = require('./scripts/topics');
const { topicLabel } = require('./scripts/lib/content-paths');

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // The intro page stands alone; it belongs to no topic.
  introSidebar: ['intro'],
};

for (const topic of getTopicDirs()) {
  sidebars[`${topic}Sidebar`] = [
    {
      type: 'category',
      label: topicLabel(topic),
      // Large topics start collapsed so the sidebar stays scannable.
      collapsed: shouldCollapseTopic(topic),
      collapsible: true,
      items: [{ type: 'autogenerated', dirName: topic }],
    },
  ];
}

module.exports = sidebars;
