const { getTopicDirs } = require('./scripts/topics');

/**
 * Builds one sidebar per topic folder under docs/, each scoped to only
 * that topic's files. The Introduction page has its own dedicated sidebar
 * so it doesn't pull in unrelated topics.
 *
 * Adding a new topic later is just "add a folder under docs/ with a
 * _category_.json" - no manual edits needed here.
 */
const sidebars = {
  // Dedicated sidebar for the Introduction page
  introSidebar: ['intro'],
};

for (const topic of getTopicDirs()) {
  sidebars[`${topic}Sidebar`] = [
    {
      type: 'category',
      label: topic.charAt(0).toUpperCase() + topic.slice(1),
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: topic }],
    },
  ];
}

module.exports = sidebars;
